; Device attr section
[DEV]
; enFormat determines the data format of the sample, only supports S16_LE now.
; 0[S16_lE]
enFormat = 0
; enSoundMode determines the channel count of Channel Group.
; 1[Mono] 2[Stereo] 4[4Chn] 6[6Chn] 8[8Chn]
enSoundMode = 2
; enSampleRate determines the sample rate of AI Device.
; 8000[8KHz] 16000[16KHz] 32000[32KHz] 48000[48KHz]
enSampleRate = 8000
; u32PeriodSize determines the count of sample in a AI Buffer
u32PeriodSize = 1024
; bInterleaved determines the data arrangement mode of each channel.
; if bInterleaved = 1, Data on each channel is interleaved, Otherwise, data on each channel is stored separately.
bInterleaved = 0
; attach interface
; 1[ADC_AB] 2[ADC_CD] 3[DMIC_A_01] 4[DMIC_A_23] 
; 5[I2S_A_01] 6[I2S_A_23] 7[I2S_A_45] 8[I2S_A_67] 9[I2S_A_89] 10[I2S_A_ab] 11[I2S_A_cd] 12[I2S_A_ef]
; 13[I2S_B_01] 14[I2S_B_23] 15[I2S_B_45] 16[I2S_B_67] 17[I2S_B_89] 18[I2S_B_ab] 19[I2S_B_cd] 20[I2S_B_ef]
; 21[I2S_C_01] 22[I2S_C_23] 23[I2S_C_45] 24[I2S_C_67] 25[I2S_C_89] 26[I2S_C_ab] 27[I2S_C_cd] 28[I2S_C_ef]
; 29[I2S_D_01] 30[I2S_D_23] 31[I2S_D_45] 32[I2S_D_67] 33[I2S_D_89] 34[I2S_D_ab] 35[I2S_D_cd] 36[I2S_D_ef]
; 37[ECHO_A] 38[HDMI_A]
aenAiIfs={1,5}

; I2S RX attr section
; It is not necessarywhen you're not using I2S RX
[I2S_X]
; enMode determines the working mode of I2S Rx
; 0[I2S Master] 1[I2S Slave] 2[Tdm Master] 3[Tdm Slave]
enMode = 0
; enBitWidth determines the bit with of I2S Rx
; 0[16 bit] 1[32bit]
enBitWidth = 0
; enFormat determines the waveform alignment of I2S Rx
; 0[I2S Philips] 1[I2S Left-justify]
enFormat = 0
; enSampleRate determines the sample rate of I2S Rx
; 8000[8KHz] 16000[16KHz] 32000[32KHz] 48000[48KHz]
enSampleRate = 8000
; enMclk determines the frequency of Mclk
; 0[disable Mclk] 1[12.288M] 2[16.384M] 3[18.432M] 4[24.576M] 5[24M] 6[48M]
enMclk = 0
; bSyncClock: 0[4-wire mode] 1[6-wire mode]
bSyncClock = 0
; u32TdmSlots determines the slot number of I2S Rx
u32TdmSlots = 2
