; Device attr section
[DEV]
; enFormat determines the data format of the sample, only supports S16_LE now.
; 0[S16_lE]
enFormat = 0
; enSoundMode determines the sound mode of AO Device.
; 1[Mono] 2[Stereo]
enSoundMode = 2
; enSampleRate determines the sample rate of AO Device.
; 8000[8KHz] 16000[16KHz] 32000[32KHz] 48000[48KHz]
enSampleRate = 8000
; u32PeriodSize(samples) determines the time to start RDMA.
u32PeriodSize = 1024
; enChannelMode determines the channel mode of AO Device.
; 0[Stereo] 1[Double Mono] 2[Double Left] 3[Double Right] 4[Exchange] 5[Only Left] 6[Only Right]
enChannelMode = 0
; attach interface
; 1[DAC_AB] 2[DAC_CD] 4[I2S_A] 8[I2S_B] 16[ECHO_A] 32[HDMI_A]
; if you want to attach DAC_AB and DAC_CD, so enAoIfs = DAC_AB | DAC_CD = 1 | 2 = 3.
enAoIfs = 5

; I2S TX attr section
; It is not necessarywhen you're not using I2S TX
[I2S_A]
; enMode determines the working mode of I2S Tx
; 0[I2S Master] 1[I2S Slave] 2[Tdm Master] 3[Tdm Slave]
enMode = 0
; enBitWidth determines the bit with of I2S Tx
; 0[16 bit] 1[32bit]
enBitWidth = 0
; enFormat determines the waveform alignment of I2S Tx
; 0[I2S Philips] 1[I2S Left-justify]
enFormat = 0
; enSampleRate determines the sample rate of I2S Tx
; 8000[8KHz] 16000[16KHz] 32000[32KHz] 48000[48KHz]
enSampleRate = 8000
; enMclk determines the frequency of Mclk
; 0[disable Mclk] 1[12.288M] 2[16.384M] 3[18.432M] 4[24.576M] 5[24M] 6[48M]
enMclk = 0
; bSyncClock: 0[4-wire mode] 1[6-wire mode]
bSyncClock = 0
; u32TdmSlots determines the slot number of I2S Tx
u32TdmSlots = 2